name: build-xs-rolling

on:
  push:
    branches:
      - rolling
  pull_request:
    branches:
      - rolling
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  xs-rolling:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: rolling, ROS_REPO: main}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout ROS Toolboxes
        uses: actions/checkout@v2
        with:
          submodules: recursive
          path: src/interbotix_ros_toolboxes
      - name: Checkout ROS Core
        uses: actions/checkout@v2
        with:
          repository: interbotix/interbotix_ros_core
          ref: rolling
          submodules: recursive
          path: src/interbotix_ros_core
      - name: ROS-I CI
        uses: ros-industrial/industrial_ci@master
        with:
          config: ${{toJSON(matrix.env)}}
